// Generated by gencpp from file record/lonlat.msg
// DO NOT EDIT!


#ifndef RECORD_MESSAGE_LONLAT_H
#define RECORD_MESSAGE_LONLAT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace record
{
template <class ContainerAllocator>
struct lonlat_
{
  typedef lonlat_<ContainerAllocator> Type;

  lonlat_()
    : lon(0.0)
    , lat(0.0)  {
    }
  lonlat_(const ContainerAllocator& _alloc)
    : lon(0.0)
    , lat(0.0)  {
  (void)_alloc;
    }



   typedef float _lon_type;
  _lon_type lon;

   typedef float _lat_type;
  _lat_type lat;




  typedef boost::shared_ptr< ::record::lonlat_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::record::lonlat_<ContainerAllocator> const> ConstPtr;

}; // struct lonlat_

typedef ::record::lonlat_<std::allocator<void> > lonlat;

typedef boost::shared_ptr< ::record::lonlat > lonlatPtr;
typedef boost::shared_ptr< ::record::lonlat const> lonlatConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::record::lonlat_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::record::lonlat_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace record

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'record': ['/home/ubuntu/qt_ros_ws/src/record/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::record::lonlat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::record::lonlat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::record::lonlat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::record::lonlat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::record::lonlat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::record::lonlat_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::record::lonlat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "efe88e83fa64b7150dd2703ea6640d94";
  }

  static const char* value(const ::record::lonlat_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xefe88e83fa64b715ULL;
  static const uint64_t static_value2 = 0x0dd2703ea6640d94ULL;
};

template<class ContainerAllocator>
struct DataType< ::record::lonlat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "record/lonlat";
  }

  static const char* value(const ::record::lonlat_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::record::lonlat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32  lon\n\
float32  lat\n\
";
  }

  static const char* value(const ::record::lonlat_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::record::lonlat_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lon);
      stream.next(m.lat);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lonlat_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::record::lonlat_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::record::lonlat_<ContainerAllocator>& v)
  {
    s << indent << "lon: ";
    Printer<float>::stream(s, indent + "  ", v.lon);
    s << indent << "lat: ";
    Printer<float>::stream(s, indent + "  ", v.lat);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RECORD_MESSAGE_LONLAT_H
